// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcPortfolio.Data;

#nullable disable

namespace MvcPortfolio.Migrations
{
    [DbContext(typeof(MvcPortfolioContext))]
    [Migration("20260103153829_TickerExchangeConnection")]
    partial class TickerExchangeConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcPortfolio.Models.Exchange", b =>
                {
                    b.Property<string>("ExchangeString")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("AVCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RatioToOne")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExchangeString");

                    b.ToTable("Exchange");
                });

            modelBuilder.Entity("MvcPortfolio.Models.Ticker", b =>
                {
                    b.Property<string>("TickerString")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ExchangeString")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TickerString");

                    b.HasIndex("ExchangeString");

                    b.ToTable("Ticker");
                });

            modelBuilder.Entity("MvcPortfolio.Models.Ticker", b =>
                {
                    b.HasOne("MvcPortfolio.Models.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeString")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });
#pragma warning restore 612, 618
        }
    }
}
